name: docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-rtd-dropdown-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-rtd-dropdown-
      - run: pip install mkdocs-rtd-dropdown
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build Docs
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - run: mkdocs gh-deploy --force
